### ISSUE TITLE
Add endogenous deployment of grid batteries

### ISSUE THREAD

**Issue by robbieorvis** [EnergyInnovation/eps-us#206]
We've contemplated the idea of allowing battery storage to be a type of power plant in the EPS, but in the past the costs haven't necessarily warranted this. Given how costs have fallen, battery storage is now competitive as a way of meeting peak demand. Lazard's recent analysis shows that on an energy basis, the two technologies are quite cost competitive. We should consider adding battery storage as a type of power plant to the model to meet peak demand. 

We can use capital costs in the model, which already represent a 4 hour battery (in line with the type of storage we are talking about). We have capacity factor data from Lazard. We would need to build in the subsidy variables. We might need a new set of shareweights just for peaker plants, because we don't want storage to be built for energy demand for now. There are probably other factors as well.

If we were to add this in, we could remove the need for BAU data for this file which is always super hard to find anyway. It would also let us explore things like how subsidies for storage or policies related to natural gas peaker plants might affect deployment.

On a related but separate topic, we may want to to revisit also adding renewables + storage as types of power plants to the model, principally solar + storage, onshore wind + storage, and offshore wind + storage. These would have higher LCOEs but would not be affected by curtailment and could contribute to meeting peak demand. As the grid is decarbonized the model would move to choosing these because they would be unaffected by curtailment.

**Comment by jrissman** [comment]
Let's revisit this issue once we've rebuilt the power sector to use hourly dispatch to see how much of this is still relevant.  Note that the model already reduces peak power demand based on grid battery capacity (and based on other things, like EV batteries, demand response, etc.).  The only thing it doesn't do is deploy more grid batteries instead of peaker power plants.  We might be able to include grid batteries in this logit allocation without making them a power plant type.

**Comment by jrissman** [comment]
Megan and I discussed this today.  It would not be wise or feasible to treat batteries as a power plant type ("Electricity Source") due to numerous assumptions baked into the structure about power plants.  Grid batteries are currently implemented and are working in the demand-shifting section, similar to other demand-shifting technologies.

We can get endogenous deployment of grid batteries using a dedicated mechanism for that purpose.  A simple approach is to take the difference between the electricity demand net peak and net trough (perhaps averaged over the year, to reflect the fact that batteries' value will be derived from their total use during the year, not just on the peak day).  Then we have a coefficient that indicates how much battery capacity is deployed in proportion to the difference between the peak and the trough, perhaps expressed as a percentage of total electricity system capacity, so that the same ballpark coefficient works in both large and small EPS model regions.  We can make the endogenous grid battery deployment mechanism more complicated from there if needed.

**Comment by mkmahajan** [comment]
I have not yet added a financing lever for batteries (issue #72), which would need to be separate from the power plant lever that is subscripted by power plant type.

I'm noting here that when we address this issue, we will want to add a corresponding financing lever.
