### ISSUE TITLE
Add web app graphs for building emissions by end use and building

### ISSUE THREAD

**Issue by robbieorvis** [EnergyInnovation/eps-us#260]
One set of graphs that would be helpful is direct and indirect building emissions by end use. Right now we only have building sector graphs for energy, but I've found myself needing/making these graphs a few times lately. I'm thinking of the following:

Within a new tier for Buildings: Emissions we could have two graphs:
Direct Building Sector Emissions by End Use [building type, building component]
Building Sector Emissions by End Use with Apportioned Electricity Emissions [building type, building component]

**Comment by jrissman** [comment]
Given that there are only four graphs in "Buildings: Energy Use" we might avoid introducing a new top-level category and renaming the existing category to "Buildings: Energy Use and Emissions" then putting the new graphs into that category.  (We were trying to avoid having more than 20 items in any drop-down menu to avoid seeing scroll bars on the nav in the old app, and the top-level menu is close to that limit.  It may not matter as much for the new app.)

The existing building energy use graphs have separate graphs breaking down energy use by building type and by building component.  These newly requested graphs appear to want to stack the building components for each building type into a single graph, which would be a lot of data series, and would be non-parallel with the existing energy use graphs.  I think this would be the first instance of us stacking the entries from two different subscripts in the same graph (except for passenger/cargo and vehicle type in the vehicle graphs).  There are dozens of instances where we could be stuffing multiple subscripts into one stacked area graph instead of making two graphs, but we've consistently been making them as separate graphs across all sectors and outputs in the web app.  Do we care about being consistent, rather than starting to include two subscripts in the same stacked area graph in just these two graphs and nowhere else in the web app?  Our design philosophy has been to keep the web app graphs a bit simpler and let users go to Vensim if they need the detailed cross-tab breakouts.  So if we're to keep with our existing philosophy, we'd be adding four graphs, not two, to cover emissions by building type and emissions by end use, with and without apportioned electricity emissions.

**Comment by robbieorvis** [comment]
Okay, makes sense to collapse into a single building sector first tier menu.

My philosophy for this is that it seems helpful to be able to show policymakers where building emissions are coming from both direct and adding in indirect emissions. Doing that in separate graphs reduces the number of things but it also makes it hard to contextualize. Someone would have to switch between the building types to try and assess the relative magnitude of say, commercial heating vs residential heating. If they are all on one graph together, that makes it easier to compare, even though there are more total items in the graphic. (though at 15 it will still be considerably less than the number of industry entries, for example).

I made a slightly different version of this graphic, building emissions by fuel, for the NDC note, which I thought was a nice addition, so that’s the direction was I was trying to go here (also, perhaps we should add this one, emissions by end use and fuel type, to the list). Hopefully this goes through to Github:

***@***.***

**Comment by jrissman** [comment]
The graphic didn't come through by email.  You can include images if you use GitHub website and posted in the issue thread via a browser.

I'm okay with adding them as two graphs with two subscripts stacked in each graph.  I do see the utility.

**Comment by robbieorvis** [comment]
Okay, no need to for now since it sounds fine by you.

**Comment by mkmahajan** [comment]
I've added the two graphs Robbie noted above, but keeping the terminology "reallocated energy carriers" since there may be emissions from the district heat and hydrogen sectors as well. 

I can't see the other potential graph Robbie mentioned in his follow-up note through email, but I think it may be this one from the NDC research note:
![image](https://github.com/EnergyInnovation/eps-us/assets/56732097/65933013-d2d6-4c11-bafa-1d9c87c1fffe)

This one strikes me as maybe too much information for one graph because we'd also need to add in other fuel types that might be used in other regions like biomass and kerosene, plus indirect emissions from heat and hydrogen production (even if most of those wouldn't need to be displayed in the web app for most regions). If we need this level of detail, maybe we could have a direct emissions by fuel and end use graph as well as an indirect emissions by fuel and end use graph?

**Comment by robbieorvis** [comment]
Yes, this is the graph, but I also agree it might be too much information. I think the most data we currently have in a graph is for the industry graphs with 25. I'm not sure I like breaking apart indirect and direct, since part of the goal is to see the two together in one graph for scale. We could potentially lose the fuels or something. The only indirect emissions should be for electricity, district heat, and hydrogen. Maybe we combine them?

**Comment by mkmahajan** [comment]
A version of this graph without the fuels component is essentially one of the two graphs I already added (building sector emissions by building type and end use with reallocated energy carriers). Is that sufficient?

**Comment by robbieorvis** [comment]
I think so! Maybe you can show me during our next check in.

**Comment by mkmahajan** [comment]
Robbie and I chatted about this, and the two new graphs are likely sufficient for now. If time permits after other development, we could consider coming back and adding three additional graphs for each building type which shows emissions by fuel type (including indirect emissions from electricity, heat, and hydrogen).
