### ISSUE TITLE
Update methodology and data for industry CCS

### ISSUE THREAD

**Issue by robbieorvis** [EnergyInnovation/eps-us#285]
Currently, we track industry CCS in two buckets: energy CCS and process CCS, for each industry. Additionally, we use a single industry wide CCS cost to measure cost impacts of CCS.

First, we should move to tracking different costs across different industries, reflecting the comparative capture costs for each. For example, it is much cheaper to capture CO2 in industries with relatively pure streams (like ethanol) as opposed to capturing energy CO2, which is more diffuse. I was able to obtain a copy of the GaffneyCline tool used by DOE to compute its US CCUS supply curve. It's attached here: 
[Carbon_Capture_Cost_Assessment1.zip](https://github.com/EnergyInnovation/eps-us/files/12173672/Carbon_Capture_Cost_Assessment1.zip). It has all the necessary data to add detail to CCS by industry (including for industries that only have energy combustion CO2 and no process CO2). We would need a structural update for the cost data to map the costs onto each of the industries tracked in the model, supported by this dataset. Additionally, this report from NETL has a lot of detail on technology used in different industries to capture CO2, where the capture equipment goes, and the relative purity of the CO2: https://www.netl.doe.gov/projects/files/CostofCapturingCO2fromIndustrialSources_071522.pdf

Second, we probably should reconsider our handling of energy vs process CCS as we revisit the structure of industry energy and emissions. Our prior assumption was that process CO2 could be captured separately from energy CO2. Today, however, energy CO2 and process CO2 are typically comingled in a single stack via the flue gas, which means that these are not separable, but combined flue gases with higher purity sources may be cheaper to capture. This is reflected in the GaffneyCline data. We should consider combining energy and process CO2 into a single value for CCS capture, where there difference in the CO2 concentration is reflected via different costs.

We discussed that in the future, there may be technology changes that change this dynamic, such as moving to an electric rotary kiln for cement manufacture, in which case there would only be process CO2 and no energy CO2, lowering capture costs due to higher CO2 concentration in the flue gas. To correctly capture these dynamics we may need to add technologies to the industry sector (or certain subsectors) in the future, for example adding some detail on non-boiler process heat that differentiates technologies for key sectors, e.g. cement kilns, BF-BOF vs EAF-DRI, etc... These changes are likely to be required anyway in order to correctly handle feedstock decarbonization, so mostly I am flagging that when we do that, we can carry it through to how we handle CCS.

**Comment by jrissman** [comment]
Thanks for this, Robbie.  This is very clear.  This sounds like a good thing to do along with the larger industry sector update.

I think we can use your dataset to identify a cost of CO2 capture for each relevant plant type today.  If it's not practical today to capture only process or only combustion CO2 (say, from a cement kiln), we can simplify the CCS lever to target all CO2 emissions from a given industry, no longer subscripted by process or energy-related emissions.  Then, the way to cause CCS to target specifically process emissions would be to fuel shift that industry to electricity or hydrogen, leaving only process CO2 available to be captured.

We also need to identify a cost of CO2 capture for a plant that has electrified its heat, so it's just process CO2 remaining.  Then, when CO2 capture is applied to a given industry in the EPS in a future year, we linearly scale the CO2 capture cost between the "today" cost and the "electrified" cost, based on the share of energy used for process heating that has been electrified. ( Given our new industrial process breakout, we can identify specifically what energy was used for process heating versus for other purposes.)

Scaling the cost this way doesn't imply a linear relationship between capture cost and CO2 concentration within a single plant because the cost and amount of CO2 captured are summed across all plants in a given industry, each one of which will either be using entirely fossil fuels or entirely electricity for heating, not a mixture.  So the linear relationship I'm suggesting is meant to reflect progress on electrifying a share of all (say, cement) plants, not changes in CO2 concentration within any specific plant.

**Comment by robbieorvis** [comment]
I think the DOE report will be helpful for that because it identifies different capture technologies based on the concentration level of CO2, so we could have different approaches for different concentrations (binned into a few categories).

**Comment by mkmahajan** [comment]
While working on other CCS data, I went ahead and modified industry CCS costs to be subscripted by emissions type and industry using the data source above. I think this will be a big improvement in accuracy for the short term, and we can revisit the question of whether we should be splitting CCS into energy vs. process emissions in a later update.
