### ISSUE TITLE
Buildings, heat impacted by carbon pricing

### ISSUE THREAD

**Issue by dobrien13** [EnergyInnovation/eps-us#308]
Request from Agora - is this possible to add on with similar structure when Jeff updates carbon pricing's impact on industry?

**Comment by dobrien13** [comment]
@jrissman see the above comment from Agora on tying carbon pricing in buildings/heat to electrification

**Comment by jrissman** [comment]
@dobrien13 The buildings sector efficiency of new components and use of existing components are already driven by fuel prices (including carbon pricing) and have been for many years.

Price-driven fuel shifting in the buildings sector is already covered in issue #10, making this issue a duplicate.

If "heat" refers to district heat plants, then I am doubtful that fuel price is the primary driver of district heat plants' choice of whether to replace their natural gas or coal systems with electric heat pumps, as they probably would want to use industrial waste heat as the heat source, and industrial waste heat will be supply-constrained.  That said, I have not looked into district heating plants closely, since they are not very important in most places.  If you see a role for fuel shifting of district heat plants driven purely by fuel/carbon prices (i.e., not driven by a mandate or political target, for which we already have regulatory a policy lever in the district heating sector), please open a new issue requesting that feature specifically.  Ideally, include links to some input data or useful information on fuel price-driven fuel shifting of district heating plants (if no such information exists, this would tend to suggest the effect is unlikely and not worth modeling).
