### ISSUE TITLE
Consider lowering PTCF for plant types bidding at peak capacities

### ISSUE THREAD

**Issue by robbieorvis** [EnergyInnovation/eps-us#35]
It appears nuclear is running at 100% capacity factor, but it should probably be a bit lower than this (actual is 92%). Not sure why, but should be an easy fix.

**Comment by jrissman** [comment]
It's because you enabled the boolean "BDSBaPCF Boolean Do Suppliers Bid at Peak Capacity Factors" for nuclear, and you gave nuclear a peak time capacity factor of 1 (in elec/PCTF), which exceeds its BAU Expected Capacity Factor (BECF) of 0.922.  If the reason it's less than 1 is because of unavoidable maintenance needs, then perhaps nuclear should not bid at its PTCF, because the plant operators know they will sometimes need maintenance (and will instead bid at BECF, which is 92.2%.  Note this is also the way you have other plant types, like coal, set up, so they would also dispatch at 100% if it were cost-effective for them to do so.  You might consider lowering PTCFs to account for unavoidable maintenance needs.

**Comment by mkmahajan** [comment]
I have changed elec/BDSBaPCF so that nuclear does not bid at its PTCF (and instead bids at its BECF, which is 92.2%). In the future, we may consider lowering PTCF for other plant types that are selected to bid at the peak capacities so that values account for unavoidable maintenance needs (coal, natural gas, biomass, lignite, and municipal solid waste).

**Comment by robbieorvis** [comment]
No longer relevant with 4.0. Closing.
