### ISSUE TITLE
Allow fuel price changes to drive industrial fuel switching in new equipment

### ISSUE THREAD

**Issue by jrissman** [EnergyInnovation/eps-us#9]
Allow changes in the fuel price caused by policies (like carbon tax, fuel taxes, and fuel price deregulation) to change industries' choice about which type of fuel newly-purchased equipment should use.

This would build on the implementation of a stock-turnover model for industrial equipment required by issue #8.

Fuel type selection could either be handled by an ALLOCATE AVAILABLE function with appropriately-defined bell curves, or it could be handled by a table of elasticities that specifies the elasticity of shifting to each fuel from each other fuel with respect to the change in the difference in price between those two fuels.  (We don’t want to handle only shifts to lower-carbon fuels, to cover the case where someone puts a tax on natural gas but not on coal, for example.)

**Comment by robbieorvis** [comment]
I thought of one data source we could possibly use for this, which is to look at AEO 2020's carbon fee scenarios and compare fuel consumption of different fuels in different industries in the scenarios to the reference scenario. A quick look though suggests that for the most part the net effect of the carbon fee is just to reduce energy consumption. We might be able to use the tables on energy consumption per unit of output to estimate endogenously driven efficiency improvement from fuel price changes (in a different issue) but it looks like at least for the US there is very little, if any fuel switching from a carbon price (likely due to the fact that given the fuel price differences between gas and electricity - there is almost no coal used in the industry sector - even with a modest carbon price the fuel switching cost is still very uneconomic. We might plausibly then assume that it's unlikely to get cost driven fuel-shifting in industry.

**Comment by robbieorvis** [comment]
Also, FWIW, if we ever wanted to cross-reference demand changes in response to changing energy prices, we could see how the change in value of shipments by industry changes in response to changes in fuel prices in the carbon fee scenarios.

**Comment by jrissman** [comment]
Completed.
