### ISSUE TITLE
Hydrogen power plants

### ISSUE THREAD

**Issue by robbieorvis** [EnergyInnovation/eps-us#99]
For a future model update, add hydrogen power plants as a power plant type. There are several ongoing projects around the country, and this is one technology that is being touted as being able to help decarbonize the last 10% of the power sector. Suggested by Bruce Nilles and Mike O'Boyle

**Comment by jrissman** [comment]
For decarbonizing the last 10% of the grid, the main strategies I'm aware of are:

- "Overbuild" cheap wind and solar, and curtail it during other parts of the year
- Make green hydrogen, then burn it for power
- Store the power in chemical batteries (and some pumped hydro, compressed air, etc.)
- Use natural gas peaker plants + CCS

Power plants burning green hydrogen are going to be very inefficient because of energy losses when burning the hydrogen (and also when making the hydrogen), so some of the other techniques might be preferable.  However, since hydrogen power plants are of interest to some policymakers (e.g., South Korea, etc.), it might be useful to add them if the EPS is able to show that they are a very expensive option compared to some of the other alternatives noted above (i.e. high-cost on the cost curve graph).
